# Generated by Django 5.2.17 on 2026-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom complet")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Téléphone"
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("infrastructure", "Infrastructure"),
                            ("btp", "BTP"),
                            ("transport", "Transport & Logistique"),
                            ("numerique", "Numérique"),
                            ("agroalimentaire", "Agroalimentaire"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Secteur concerné",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="E-mail envoyé"),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
